/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_com_neoquest_voting_crypt_Encrypter
#define _Included_com_neoquest_voting_crypt_Encrypter
#ifdef __cplusplus
extern "C" {
#endif
	 
JNIEXPORT void JNICALL Java_com_neoquest_voting_crypt_Encrypter_keyGen(JNIEnv, jobject, jcharArray, jcharArray, jcharArray);
JNIEXPORT void JNICALL	Java_com_neoquest_voting_crypt_Encrypter_encrypt(JNIEnv*, jobject, jcharArray, jcharArray, jcharArray, jcharArray);
	 
JNIEXPORT void JNICALL Java_com_neoquest_voting_crypt_Encrypter_decrypt(JNIEnv*, jobject, jcharArray, jcharArray, jcharArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif